### ISSUE TITLE
where is the documentation ?

### ISSUE THREAD

**Issue by mhetru** [h2lsoft/Tpln#1]
Hello,

i have learned TPLN in 2004 with the Learning Managing System who named "ENFASE".

and i want now teach a collaborator in my job on the separated templates feature in one hand and controller feature in other hand, but the website  http://tpln.h2lsoft.com/ is down and the documentation is not available on the git repository.

can you upload the documentation with the examples on the git repository ? please ?

thanks!

**Comment by mhetru** [comment]
Hello,

i have found the archive on wayback machine : https://web.archive.org/web/20120714063717/http://tpln.h2lsoft.com/

**Comment by h2lsoft** [comment]
Sorry for this inconvenience, website is up now

**Comment by mhetru** [comment]
thanks !!!!
